# generated by AI

import os
import time

filename = "saved_models/agent1.pth"
# filename = "saved_games/episode_800.hgpn"

# Get the last modified time of the file
modified_time = os.path.getmtime(filename)
print("Last modified:", time.ctime(modified_time))


